export function decodeHTMLEntities(text: string) {
  const entities = [
    ['amp', '&'],
    ['apos', "'"],
    ['lt', '<'],
    ['gt', '>'],
    ['Agrave', 'À'],
    ['Aacute', 'Á'],
    ['Acirc', 'Â'],
    ['Atilde', 'Ã'],
    ['Auml', 'Ä'],
    ['Aring', 'Å'],
    ['AElig', 'Æ'],
    ['Ccedil', 'Ç'],
    ['Egrave', 'È'],
    ['Eacute', 'É'],
    ['Ecirc', 'Ê'],
    ['Euml', 'Ë'],
    ['Igrave', 'Ì'],
    ['Iacute', 'Í'],
    ['Icirc', 'Î'],
    ['Iuml', 'Ï'],
    ['ETH', 'Ð'],
    ['Ntilde', 'Ñ'],
    ['Ograve', 'Ò'],
    ['Oacute', 'Ó'],
    ['Ocirc', 'Ô'],
    ['Otilde', 'Õ'],
    ['Ouml', 'Ö'],
    ['Oslash', 'Ø'],
    ['Ugrave', 'Ù'],
    ['Uacute', 'Ú'],
    ['Ucirc', 'Û'],
    ['Uuml', 'Ü'],
    ['Yacute', 'Ý'],
    ['THORN', 'Þ'],
    ['szlig', 'ß'],
    ['agrave', 'à'],
    ['aacute', 'á'],
    ['acirc', 'â'],
    ['atilde', 'ã'],
    ['auml', 'ä'],
    ['aring', 'å'],
    ['aelig', 'æ'],
    ['ccedil', 'ç'],
    ['egrave', 'è'],
    ['eacute', 'é'],
    ['ecirc', 'ê'],
    ['euml', 'ë'],
    ['igrave', 'ì'],
    ['iacute', 'í'],
    ['icirc', 'î'],
    ['iuml', 'ï'],
    ['eth', 'ð'],
    ['ntilde', 'ñ'],
    ['ograve', 'ò'],
    ['oacute', 'ó'],
    ['ocirc', 'ô'],
    ['otilde', 'õ'],
    ['ouml', 'ö'],
    ['oslash', 'ø'],
    ['ugrave', 'ù'],
    ['uacute', 'ú'],
    ['ucirc', 'û'],
    ['uuml', 'ü'],
    ['yacute', 'ý'],
    ['thorn', 'þ'],
    ['yuml', 'ÿ'],
    ['nbsp', ' '],
    ['iexcl', '¡'],
    ['cent', '¢'],
    ['pound', '£'],
    ['curren', '¤'],
    ['yen', '¥'],
    ['brvbar', '¦'],
    ['sect', '§'],
    ['uml', '¨'],
    ['copy', '©'],
    ['ordf', 'ª'],
    ['laquo', '«'],
    ['not', '¬'],
    ['shy', '\xAD'],
    ['reg', '®'],
    ['macr', '¯'],
    ['deg', '°'],
    ['plusmn', '±'],
    ['sup2', '²'],
    ['sol', '/'],
  ];

  for (let i = 0, max = entities.length; i < max; ++i) {
    text = text.replace(new RegExp('&' + entities[i][0] + ';', 'g'), entities[i][1]);
  }

  return text;
}
